// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnccIGIFqDujTO-0FB6JabCG1XzxXHtCY',
    appId: '1:493343029699:web:2aff81181e34d7f45ea576',
    messagingSenderId: '493343029699',
    projectId: 'pharmacy-guide-6a80f',
    authDomain: 'pharmacy-guide-6a80f.firebaseapp.com',
    storageBucket: 'pharmacy-guide-6a80f.appspot.com',
    measurementId: 'G-JT2RWP96KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBplOvWM17Bi7rJdVKLI9wrc4DbFGygK4o',
    appId: '1:493343029699:android:195eeec00a698c235ea576',
    messagingSenderId: '493343029699',
    projectId: 'pharmacy-guide-6a80f',
    storageBucket: 'pharmacy-guide-6a80f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-nlKwnV1jGlCfil3NzArJNz-7OcVP4bQ',
    appId: '1:493343029699:ios:8dbfaaa7b57520e75ea576',
    messagingSenderId: '493343029699',
    projectId: 'pharmacy-guide-6a80f',
    storageBucket: 'pharmacy-guide-6a80f.appspot.com',
    iosBundleId: 'com.yho.pharmacyguide2.pharmacyGuide2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnccIGIFqDujTO-0FB6JabCG1XzxXHtCY',
    appId: '1:493343029699:web:ea530be14c4c1b1c5ea576',
    messagingSenderId: '493343029699',
    projectId: 'pharmacy-guide-6a80f',
    authDomain: 'pharmacy-guide-6a80f.firebaseapp.com',
    storageBucket: 'pharmacy-guide-6a80f.appspot.com',
    measurementId: 'G-Y7YL9VQYJ1',
  );
}
